# Use the lightweight Alpine-based Nginx image as the base image
FROM nginx:1.20.2-alpine

# Copy the production Nginx configuration into the container
COPY ./default-prod-ssl.conf /etc/nginx/conf.d/default.conf

# Copy the Gzip compression configuration
COPY ./gzip.conf /etc/nginx/conf.d/gzip.conf

# Create the static directory in the container
RUN mkdir -p /var/www/app/static && \
    chmod 755 /var/www/app/static